### ISSUE TITLE
1.4.1 Binary - failed to execute script

### ISSUE THREAD

**Issue by KhanSW** [evertonstz/pynps#8] opened 2020-03-31 19:26 UTC
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth__tkinter.py", line 30, in <module>
FileNotFoundError: Tcl data directory "/tmp/_MEIw55QPa/tcl" not found.
[27062] Failed to execute script pyi_rth__tkinter

**Comment by evertonstz** [comment] 2020-04-01 18:24
Will need more info than that.
Will need: OS and python version (unless you're using binaries).

**Comment by evertonstz** [comment] 2020-04-14 17:14
Since I can't reproduce it and OP never came back to give more information about the bug, I'm closing the issue. If anyone ever faces this same bug please feel free to reopen this issue or make a new one.

**Closed by evertonstz** 2020-04-14 17:14 UTC

**Comment by irockdude554** [comment] 2024-08-04 18:51
im getting the same issue on my steam deck running bazzite os which is fedora based

**Comment by evertonstz** [comment] 2024-08-21 12:08
> im getting the same issue on my steam deck running bazzite os which is fedora based

You're using the pip version?
